version: "3.8"

services:
  kawa-products-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: products
      POSTGRES_PASSWORD: kawaproducts
      POSTGRES_DB: kawaproductsdb
    ports:
      - "3250:5433"
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - kawa-products-network

  tasks-app:
    container_name: tp_integration_continue
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - tasks-db
    environment:
      - DATABASE_URL=postgresql://products:kawaproducts@kawa-products-db/kawaproductsdb
    networks:
      - kawa-products-network

  # tasks-test:
  #   build: .
  #   depends_on:
  #     - tasks-db
  #   environment:
  #     - DATABASE_URL=postgresql://taskuser:taskpassword@tasks-db/taskdb
  #   command: ["pytest", "--cov=app"]
  #   networks:
  #     - tasks-network

volumes:
  data:

networks:
  kawa-products-network: