version: "3.8"

services:
  kawa-products-db:
    image: mysql:latest
    environment:
      MYSQL_USER: products
      MYSQL_PASSWORD: kawaproducts
      MYSQL_DATABASE: product_db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3308:3306" 
    expose:
      - "3306"
    volumes:
      - products-data:/var/lib/mysql
      - ./database/scripts:/docker-entrypoint-initdb.d
    networks:
      - kawa-products-network
      - kawa-shared-network

  kawa-products-app:
    container_name: kawa_products
    build:
      context: .
    ports:
      - "8080:80"
    depends_on:
      - kawa-products-db
    environment:
      - DATABASE_URL=mysql+mysqlconnector://products:kawaproducts@kawa-products-db:3306/product_db 
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672
    networks:
      - kawa-products-network
      - kawa-shared-network

volumes:
  products-data:

networks:
  kawa-products-network:
  kawa-shared-network:
    external: true