version: "3.8"

services:
  kawa-products-db:
    image: mysql:latest
    environment:
      MYSQL_USER: products
      MYSQL_PASSWORD: kawaproducts
      MYSQL_DATABASE: kawaproductsdb
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3254:3308" 
    expose:
      - "3308"  
    volumes:
      - products-data:/var/lib/mysql
    networks:
      - kawa-products-network

  kawa-products-app:
    container_name: kawa_products
    build:
      context: .
    ports:
      - "8080:80"
    depends_on:
      - kawa-products-db
    environment:
      - DATABASE_URL=mysql://products:kawaproducts@kawa-products-db:3308/kawaproductsdb
    networks:
      - kawa-products-network

volumes:
  products-data:

networks:
  kawa-products-network: