version: "3.8"

services:
  kawa-products-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: products
      POSTGRES_PASSWORD: kawaproducts
      POSTGRES_DB: kawaproductsdb
    ports:
      - "3250:5430"
    expose:
      - "5430" 
    volumes:
      - products-data:/var/lib/postgresql/data
    networks:
      - kawa-products-network

  kawa-products-app:
    container_name: kawa_products
    build:
      context: .
    ports:
      - "8080:80"
    depends_on:
      - kawa-products-db
    environment:
      - DATABASE_URL=postgresql://products:kawaproducts@kawa-products-db/kawaproductsdb
    networks:
      - kawa-products-network

volumes:
  products-data:

networks:
  kawa-products-network: